name: SmartWeatherAppCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # To run actions manually from actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Run a one-line script
        run: echo hello, world
      - name: Run a multi-line script
        run: 
          echo check lint errors,
          echo test build and generate apk.
        
    
